### ISSUE TITLE
Java error exporting playlist...

### ISSUE THREAD

**Issue by mrlatin** [schnatterer/songbirdDbTools#1]
Getting out of memory error ...

C:\Users\Ruben\Desktop\songbirdDbTools-0.2-bin\songbirdDbTools-0.2>songbirdDbTools -db "C:\Users\Ruben\AppData\Roaming\Philips-Songbird\Profiles\876ln52v.default\db" exportplaylists "c:\music\playlists" --playlists LoveSongs  --skipdynamic --relative
2015-08-28 15:21:10,118 INFO  [main] SongbirdDatabaseTools: Welcome to songbirdDbTools (v.0.2 build 20150518183505)
2015-08-28 15:21:10,188 INFO  [main] SongbirdDbConnection: Opening connection to jdbc:sqlite:C:\Users\Ruben\AppData\Roaming\Philips-Songbird\Profiles\876ln52v.default\db
2015-08-28 15:21:10,544 ERROR [main] SongbirdDatabaseTools: java.sql.SQLException: [SQLITE_CANTOPEN]  Unable to open the database file (out of memory)
java.lang.RuntimeException: java.sql.SQLException: [SQLITE_CANTOPEN]  Unable to open the database file (out of memory)
        at info.schnatterer.songbirddbapi4.SongbirdDb.<init>(SongbirdDb.java:139)
        at info.schnatterer.songbirdDbTools.SongbirdDatabaseTools.evaluateParams(SongbirdDatabaseTools.java:89)
        at info.schnatterer.songbirdDbTools.SongbirdDatabaseTools.main(SongbirdDatabaseTools.java:50)
Caused by: java.sql.SQLException: [SQLITE_CANTOPEN]  Unable to open the database file (out of memory)
        at org.sqlite.DB.newSQLException(DB.java:383)
        at org.sqlite.DB.newSQLException(DB.java:387)
        at org.sqlite.DB.throwex(DB.java:374)
        at org.sqlite.NativeDB._open(Native Method)
        at org.sqlite.DB.open(DB.java:86)
        at org.sqlite.Conn.open(Conn.java:140)
        at org.sqlite.Conn.<init>(Conn.java:57)
        at org.sqlite.JDBC.createConnection(JDBC.java:77)
        at org.sqlite.SQLiteConfig.createConnection(SQLiteConfig.java:72)
        at info.schnatterer.songbirddbapi4.SongbirdDbConnection.getConnection(SongbirdDbConnection.java:122)
        at info.schnatterer.songbirddbapi4.SongbirdDbConnection.getStatment(SongbirdDbConnection.java:143)
        at info.schnatterer.songbirddbapi4.SongbirdDbConnection.executeQuery(SongbirdDbConnection.java:167)
        at info.schnatterer.songbirddbapi4j.domain.MediaListTypes.populatelistTypeMap(MediaListTypes.java:67)
        at info.schnatterer.songbirddbapi4.SongbirdDb.<init>(SongbirdDb.java:136)

Help!!

**Comment by schnatterer** [comment]
Sorry, I must have missed that you opened this issue.

Try the following:
`songbirdDbTools -db "C:\Users\Ruben\AppData\Roaming\Philips-Songbird\Profiles\876ln52v.default\db\main@library.songbirdnest.com.db" exportplaylists "c:\music\playlists" --playlists LoveSongs --skipdynamic --relative`

**Comment by schnatterer** [comment]
No answer in five years. Probably no longer relevant.
